# Generated by Django 2.2.3 on 2019-09-02 09:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOWScrumban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('produced_by', models.CharField(blank=True, max_length=128)),
                ('date_project', models.DateField(default=datetime.date.today)),
                ('intro', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('inScope', models.TextField(blank=True)),
                ('outScope', models.TextField(blank=True)),
                ('backlog', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('iterations', models.IntegerField(blank=True)),
                ('team', models.TextField(blank=True)),
                ('wipLimit', models.IntegerField(default=1)),
                ('review', models.TextField(blank=True)),
                ('milestones', models.DateField(default=datetime.date.today)),
                ('milestone_description', models.CharField(blank=True, max_length=128)),
                ('delivery', models.DateField(default=datetime.date.today)),
                ('invoice', models.DateField(default=datetime.date.today)),
                ('invoice_info', models.CharField(blank=True, max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('firstName', models.TextField(blank=True)),
                ('date_signature1', models.DateField(default=datetime.date.today)),
                ('secondName', models.TextField(blank=True)),
                ('date_signature2', models.DateField(default=datetime.date.today)),
                ('updated', models.DateTimeField(default=datetime.date.today, verbose_name='Last updated')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOWScrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('produced_by', models.CharField(blank=True, max_length=128)),
                ('date_project', models.DateField(default=datetime.date.today)),
                ('intro', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('inScope', models.TextField(blank=True)),
                ('outScope', models.TextField(blank=True)),
                ('backlog', models.TextField(blank=True)),
                ('sprintLength', models.IntegerField()),
                ('sprint', models.IntegerField()),
                ('team', models.TextField(blank=True)),
                ('done', models.TextField(blank=True)),
                ('review', models.TextField(blank=True)),
                ('milestones', models.DateField(default=datetime.date.today)),
                ('milestone_description', models.CharField(blank=True, max_length=128)),
                ('delivery', models.DateField(default=datetime.date.today)),
                ('invoice', models.DateField(default=datetime.date.today)),
                ('invoice_info', models.CharField(blank=True, max_length=128)),
                ('amount', models.TextField()),
                ('firstName', models.TextField(blank=True)),
                ('date_signature1', models.DateField(default=datetime.date.today)),
                ('secondName', models.TextField(blank=True)),
                ('date_signature2', models.DateField(default=datetime.date.today)),
                ('updated', models.DateTimeField(default=datetime.date.today, verbose_name='Last updated')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOWKanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('produced_by', models.CharField(blank=True, max_length=128)),
                ('date_project', models.DateField(default=datetime.date.today)),
                ('intro', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('inScope', models.TextField(blank=True)),
                ('outScope', models.TextField(blank=True)),
                ('backlog', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('columns', models.IntegerField(blank=True)),
                ('column_labels', models.TextField(blank=True)),
                ('wipLimit', models.IntegerField(default=1)),
                ('delivery', models.DateField(default=datetime.date.today)),
                ('invoice', models.DateField(default=datetime.date.today)),
                ('invoice_info', models.CharField(blank=True, max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('firstName', models.TextField(blank=True)),
                ('date_signature1', models.DateField(default=datetime.date.today)),
                ('secondName', models.TextField(blank=True)),
                ('date_signature2', models.DateField(default=datetime.date.today)),
                ('updated', models.DateTimeField(default=datetime.date.today, verbose_name='Last updated')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
