# Generated by Django 2.2.3 on 2019-07-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('updated', models.DateTimeField(verbose_name='Last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.TextField(blank=True)),
                ('wipLimit', models.IntegerField()),
                ('scrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agileSPM.SOW')),
            ],
        ),
    ]
