# Generated by Django 2.2.3 on 2019-08-22 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agileSPM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOWKanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('produced_by', models.CharField(blank=True, max_length=128)),
                ('date_project', models.DateField(default=datetime.date.today)),
                ('intro', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('inScope', models.TextField(blank=True)),
                ('outScope', models.TextField(blank=True)),
                ('backlog', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('columns', models.IntegerField(blank=True)),
                ('column_labels', models.TextField(blank=True)),
                ('wipLimit', models.IntegerField(default=1)),
                ('milestones', models.DateField(default=datetime.date.today)),
                ('milestone_description', models.CharField(blank=True, max_length=128)),
                ('delivery', models.DateField(default=datetime.date.today)),
                ('invoice', models.DateField(default=datetime.date.today)),
                ('invoice_info', models.CharField(blank=True, max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('firstName', models.TextField(blank=True)),
                ('date_signature1', models.DateField(default=datetime.date.today)),
                ('secondName', models.TextField(blank=True)),
                ('date_signature2', models.DateField(default=datetime.date.today)),
                ('updated', models.DateTimeField(default=datetime.date.today, verbose_name='Last updated')),
            ],
        ),
        migrations.CreateModel(
            name='SOWScrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('produced_by', models.CharField(blank=True, max_length=128)),
                ('date_project', models.DateField(default=datetime.date.today)),
                ('intro', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('inScope', models.TextField(blank=True)),
                ('outScope', models.TextField(blank=True)),
                ('backlog', models.TextField(blank=True)),
                ('sprintLength', models.IntegerField()),
                ('sprint', models.IntegerField()),
                ('sprintPlan', models.TextField(blank=True)),
                ('team', models.TextField(blank=True)),
                ('done', models.TextField(blank=True)),
                ('review', models.TextField(blank=True)),
                ('milestones', models.DateField(default=datetime.date.today)),
                ('milestone_description', models.CharField(blank=True, max_length=128)),
                ('delivery', models.DateField(default=datetime.date.today)),
                ('invoice', models.DateField(default=datetime.date.today)),
                ('invoice_info', models.CharField(blank=True, max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('firstName', models.TextField(blank=True)),
                ('date_signature1', models.DateField(default=datetime.date.today)),
                ('secondName', models.TextField(blank=True)),
                ('date_signature2', models.DateField(default=datetime.date.today)),
                ('updated', models.DateTimeField(default=datetime.date.today, verbose_name='Last updated')),
            ],
        ),
        migrations.CreateModel(
            name='SOWScrumban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('produced_by', models.CharField(blank=True, max_length=128)),
                ('date_project', models.DateField(default=datetime.date.today)),
                ('intro', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('inScope', models.TextField(blank=True)),
                ('outScope', models.TextField(blank=True)),
                ('backlog', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('iterations', models.IntegerField(blank=True)),
                ('team', models.TextField(blank=True)),
                ('wipLimit', models.IntegerField(default=1)),
                ('review', models.TextField(blank=True)),
                ('milestones', models.DateField(default=datetime.date.today)),
                ('milestone_description', models.CharField(blank=True, max_length=128)),
                ('delivery', models.DateField(default=datetime.date.today)),
                ('invoice', models.DateField(default=datetime.date.today)),
                ('invoice_info', models.CharField(blank=True, max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('firstName', models.TextField(blank=True)),
                ('date_signature1', models.DateField(default=datetime.date.today)),
                ('secondName', models.TextField(blank=True)),
                ('date_signature2', models.DateField(default=datetime.date.today)),
                ('updated', models.DateTimeField(default=datetime.date.today, verbose_name='Last updated')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Scrum',
        ),
        migrations.DeleteModel(
            name='SOW',
        ),
        migrations.AddField(
            model_name='sowscrumban',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agileSPM.UserProfile'),
        ),
        migrations.AddField(
            model_name='sowscrum',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agileSPM.UserProfile'),
        ),
        migrations.AddField(
            model_name='sowkanban',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agileSPM.UserProfile'),
        ),
    ]
