# Generated by Django 2.2.3 on 2019-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0002_auto_20190902_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonesscrum',
            name='scrum',
        ),
        migrations.RemoveField(
            model_name='milestonesscrumban',
            name='scrumban',
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='wipLimit',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='wipLimit',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.DeleteModel(
            name='InvoiceScrum',
        ),
        migrations.DeleteModel(
            name='MilestonesScrum',
        ),
        migrations.DeleteModel(
            name='MilestonesScrumban',
        ),
    ]
