# Generated by Django 2.2.3 on 2019-07-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0002_auto_20190730_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='sow',
            name='produced_by',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
