# Generated by Django 2.2.3 on 2019-08-01 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0003_sow_produced_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumban',
            old_name='it1',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='kanban',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='kanban',
            name='column2',
        ),
        migrations.RemoveField(
            model_name='kanban',
            name='column3',
        ),
        migrations.RemoveField(
            model_name='kanban',
            name='column4',
        ),
        migrations.RemoveField(
            model_name='kanban',
            name='column5',
        ),
        migrations.RemoveField(
            model_name='kanban',
            name='column6',
        ),
        migrations.RemoveField(
            model_name='scrum',
            name='sprintBacklog1',
        ),
        migrations.RemoveField(
            model_name='scrum',
            name='sprintBacklog2',
        ),
        migrations.RemoveField(
            model_name='scrum',
            name='sprintBacklog3',
        ),
        migrations.RemoveField(
            model_name='scrum',
            name='sprintBacklog4',
        ),
        migrations.RemoveField(
            model_name='scrumban',
            name='it2',
        ),
        migrations.RemoveField(
            model_name='scrumban',
            name='it3',
        ),
        migrations.RemoveField(
            model_name='scrumban',
            name='it4',
        ),
        migrations.AddField(
            model_name='kanban',
            name='column_labels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kanban',
            name='delivery',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='scrumban',
            name='delivery',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
