# Generated by Django 2.2.3 on 2019-09-05 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0003_auto_20190903_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowkanban',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='assumptions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='backlog',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='column_labels',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='columns',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='date_project',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='date_signature1',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='date_signature2',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='deliverables',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='delivery',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='firstName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='inScope',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='invoice',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='invoice_info',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='outScope',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='plan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='produced_by',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='secondName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='updated',
            field=models.DateTimeField(default=datetime.date.today, null=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='sowkanban',
            name='wipLimit',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='amount',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='assumptions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='backlog',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='date_project',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='date_signature1',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='date_signature2',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='deliverables',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='delivery',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='done',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='firstName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='inScope',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='invoice',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='invoice_info',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='milestone_description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='milestones',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='outScope',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='produced_by',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='secondName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='sprint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='sprintLength',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='team',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrum',
            name='updated',
            field=models.DateTimeField(default=datetime.date.today, null=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='assumptions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='backlog',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='date_project',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='date_signature1',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='date_signature2',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='deliverables',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='delivery',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='firstName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='inScope',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='invoice',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='invoice_info',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='iterations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='milestone_description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='milestones',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='outScope',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='plan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='produced_by',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='secondName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='team',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='updated',
            field=models.DateTimeField(default=datetime.date.today, null=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='sowscrumban',
            name='wipLimit',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
