# Generated by Django 2.2.3 on 2019-08-22 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0003_auto_20190822_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowscrum',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
