# Generated by Django 2.2.3 on 2019-08-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0004_auto_20190801_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumban',
            name='delivery',
        ),
        migrations.AddField(
            model_name='kanban',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrumban',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='columns',
            field=models.IntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six')], default=1),
        ),
        migrations.AlterField(
            model_name='scrum',
            name='sprint',
            field=models.IntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default=1),
        ),
        migrations.AlterField(
            model_name='scrumban',
            name='iterations',
            field=models.IntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default=1),
        ),
    ]
