# Generated by Django 2.2.3 on 2019-08-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0004_auto_20190822_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowscrum',
            name='amount',
            field=models.TextField(),
        ),
    ]
