# Generated by Django 2.2.3 on 2019-08-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0005_auto_20190801_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='columns',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrum',
            name='sprint',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scrumban',
            name='iterations',
            field=models.IntegerField(blank=True),
        ),
    ]
