# Generated by Django 2.2.3 on 2019-08-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0005_auto_20190828_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sowscrum',
            name='sprintPlan',
        ),
    ]
