# Generated by Django 2.2.3 on 2019-08-29 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0006_remove_sowscrum_sprintplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sowscrum',
            name='milestone_description',
        ),
        migrations.RemoveField(
            model_name='sowscrum',
            name='milestones',
        ),
        migrations.CreateModel(
            name='MilestonesScrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestones', models.DateField(default=datetime.date.today)),
                ('milestone_description', models.CharField(blank=True, max_length=128)),
                ('scrum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agileSPM.SOWScrum')),
            ],
        ),
    ]
