# Generated by Django 2.2.3 on 2019-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0006_auto_20190801_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='sow',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
