# Generated by Django 2.2.3 on 2019-08-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0008_auto_20190801_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanban',
            old_name='kanban',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='scrum',
            old_name='scrum',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='scrumban',
            old_name='scrumban',
            new_name='title',
        ),
    ]
