# Generated by Django 2.2.3 on 2019-08-01 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0009_auto_20190801_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban',
            name='updated',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='scrum',
            name='updated',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='scrumban',
            name='updated',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='sow',
            name='invoice_info',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sow',
            name='milestone_description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sow',
            name='updated',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Last updated'),
        ),
    ]
