# Generated by Django 2.2.3 on 2019-08-02 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0010_auto_20190801_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='sow',
            name='date_signature1',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sow',
            name='date_signature2',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
