# Generated by Django 2.2.3 on 2019-08-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0014_auto_20190814_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowkanban',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agileSPM.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sowscrum',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agileSPM.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sowscrumban',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agileSPM.UserProfile'),
            preserve_default=False,
        ),
    ]
