# Generated by Django 2.2.3 on 2019-08-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agileSPM', '0016_auto_20190820_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sowkanban',
            name='firstSignature',
        ),
        migrations.RemoveField(
            model_name='sowkanban',
            name='secondSignature',
        ),
        migrations.RemoveField(
            model_name='sowkanban',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sowscrum',
            name='firstSignature',
        ),
        migrations.RemoveField(
            model_name='sowscrum',
            name='secondSignature',
        ),
        migrations.RemoveField(
            model_name='sowscrum',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sowscrumban',
            name='firstSignature',
        ),
        migrations.RemoveField(
            model_name='sowscrumban',
            name='secondSignature',
        ),
        migrations.RemoveField(
            model_name='sowscrumban',
            name='slug',
        ),
    ]
